//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/", ConfigurationName="ServiceReference1.VehicleService")]
    public interface VehicleService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.entessa.com/synthesisSchema/1/VehicleService/GetVehicle", ReplyAction="http://www.entessa.com/synthesisSchema/1/VehicleService/GetVehicleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SynthesisEntity))]
        System.Threading.Tasks.Task<ServiceReference1.WsVehicleResponse> GetVehicleAsync(ServiceReference1.WsGetVehicleRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.entessa.com/synthesisSchema/1/VehicleService/GetVehicles", ReplyAction="http://www.entessa.com/synthesisSchema/1/VehicleService/GetVehiclesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SynthesisEntity))]
        System.Threading.Tasks.Task<ServiceReference1.WsVehicleResponse> GetVehiclesAsync(ServiceReference1.WsGetVehiclesRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.entessa.com/synthesisSchema/1/VehicleService/SaveVehicle", ReplyAction="http://www.entessa.com/synthesisSchema/1/VehicleService/SaveVehicleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SynthesisEntity))]
        System.Threading.Tasks.Task<ServiceReference1.WsVehicleResponse> SaveVehicleAsync(ServiceReference1.WsSaveVehicleRequest req);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public partial class WsGetVehicleRequest : WsRequest
    {
        
        private Identifier vehicleIdField;
        
        private NBool includeVehicleCompartmentsField;
        
        private NBool includeExternalIdentifiersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public Identifier VehicleId
        {
            get
            {
                return this.vehicleIdField;
            }
            set
            {
                this.vehicleIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public NBool IncludeVehicleCompartments
        {
            get
            {
                return this.includeVehicleCompartmentsField;
            }
            set
            {
                this.includeVehicleCompartmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public NBool IncludeExternalIdentifiers
        {
            get
            {
                return this.includeExternalIdentifiersField;
            }
            set
            {
                this.includeExternalIdentifiersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public partial class Identifier
    {
        
        private NLong idField;
        
        private ExternalIdentifier externalIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public NLong Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public ExternalIdentifier ExternalId
        {
            get
            {
                return this.externalIdField;
            }
            set
            {
                this.externalIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://openseal.org/XmlSchema/1")]
    public partial class NLong
    {
        
        private long valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://openseal.org/XmlSchema/1")]
    public partial class NEnumOfAppErrorTypeEnum
    {
        
        private AppErrorTypeEnum valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AppErrorTypeEnum Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://openseal.org/XmlSchema/1")]
    public enum AppErrorTypeEnum
    {
        
        /// <remarks/>
        UNKNOWN = 1,
        
        /// <remarks/>
        VALIDATE = 2,
        
        /// <remarks/>
        BUSINESS = 4,
        
        /// <remarks/>
        MISC = 8,
        
        /// <remarks/>
        PERMISSION = 16,
        
        /// <remarks/>
        SYSTEM = 32,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://openseal.org/XmlSchema/1")]
    public partial class NEnumOfLogSeverityLevelEnum
    {
        
        private LogSeverityLevelEnum valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LogSeverityLevelEnum Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://openseal.org/XmlSchema/1")]
    public enum LogSeverityLevelEnum
    {
        
        /// <remarks/>
        CRITICAL = 1,
        
        /// <remarks/>
        ERROR = 2,
        
        /// <remarks/>
        WARN = 4,
        
        /// <remarks/>
        INFO = 8,
        
        /// <remarks/>
        TRACE = 16,
        
        /// <remarks/>
        DEBUG = 32,
        
        /// <remarks/>
        CUSTOM_WARN = 64,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://openseal.org/XmlSchema/1")]
    public partial class AppError
    {
        
        private string errorKeyField;
        
        private string messageField;
        
        private NEnumOfLogSeverityLevelEnum errorLevelField;
        
        private NEnumOfAppErrorTypeEnum errorTypeField;
        
        private NLong timeStampField;
        
        private string originalValueField;
        
        private string commandIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorKey
        {
            get
            {
                return this.errorKeyField;
            }
            set
            {
                this.errorKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public NEnumOfLogSeverityLevelEnum ErrorLevel
        {
            get
            {
                return this.errorLevelField;
            }
            set
            {
                this.errorLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public NEnumOfAppErrorTypeEnum ErrorType
        {
            get
            {
                return this.errorTypeField;
            }
            set
            {
                this.errorTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public NLong TimeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string OriginalValue
        {
            get
            {
                return this.originalValueField;
            }
            set
            {
                this.originalValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CommandId
        {
            get
            {
                return this.commandIdField;
            }
            set
            {
                this.commandIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WsVehicleResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public abstract partial class WsResponse
    {
        
        private WsAddressInfo addressInfoField;
        
        private AppError[] errorsField;
        
        private OSealProperty[] propertiesField;
        
        private WsRequest requestField;
        
        private PayloadExtensions extensionsField;
        
        private decimal schemaVersionField;
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public WsAddressInfo AddressInfo
        {
            get
            {
                return this.addressInfoField;
            }
            set
            {
                this.addressInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://openseal.org/XmlSchema/1")]
        public AppError[] Errors
        {
            get
            {
                return this.errorsField;
            }
            set
            {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://openseal.org/XmlSchema/1")]
        public OSealProperty[] Properties
        {
            get
            {
                return this.propertiesField;
            }
            set
            {
                this.propertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public WsRequest Request
        {
            get
            {
                return this.requestField;
            }
            set
            {
                this.requestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public PayloadExtensions Extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal schemaVersion
        {
            get
            {
                return this.schemaVersionField;
            }
            set
            {
                this.schemaVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public partial class WsAddressInfo
    {
        
        private string messageIdField;
        
        private string relatesToMessageIdField;
        
        private string sourceSystemIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=0)]
        public string MessageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=1)]
        public string RelatesToMessageId
        {
            get
            {
                return this.relatesToMessageIdField;
            }
            set
            {
                this.relatesToMessageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SourceSystemId
        {
            get
            {
                return this.sourceSystemIdField;
            }
            set
            {
                this.sourceSystemIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://openseal.org/XmlSchema/1")]
    public partial class OSealProperty
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WsSaveVehicleRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WsGetVehiclesRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WsGetVehicleRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public abstract partial class WsRequest
    {
        
        private WsAddressInfo addressInfoField;
        
        private OSealProperty[] propertiesField;
        
        private PayloadExtensions extensionsField;
        
        private NBool includeChildObjectsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public WsAddressInfo AddressInfo
        {
            get
            {
                return this.addressInfoField;
            }
            set
            {
                this.addressInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://openseal.org/XmlSchema/1")]
        public OSealProperty[] Properties
        {
            get
            {
                return this.propertiesField;
            }
            set
            {
                this.propertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public PayloadExtensions Extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public NBool IncludeChildObjects
        {
            get
            {
                return this.includeChildObjectsField;
            }
            set
            {
                this.includeChildObjectsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public partial class PayloadExtensions
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://openseal.org/XmlSchema/1")]
    public partial class NBool
    {
        
        private bool valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public partial class WsSaveVehicleRequest : WsRequest
    {
        
        private Vehicle vehicleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public Vehicle Vehicle
        {
            get
            {
                return this.vehicleField;
            }
            set
            {
                this.vehicleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public partial class Vehicle : SynthesisEntity
    {
        
        private Identifier vehicleIdField;
        
        private CustomFieldInstance[] customFieldInstancesField;
        
        private string vehicleCodeField;
        
        private string vehicleNameField;
        
        private string vehicleDescriptionField;
        
        private NEnumOfVehicleTypeEnum vehicleTypeField;
        
        private Identifier locationIdField;
        
        private NDecimal vehicleTareWeightField;
        
        private NDecimal vehicleWeightLimitField;
        
        private NEnumOfVehicleLoadingPositionEnum vehicleLoadingPositionField;
        
        private NDateTime expiryDateField;
        
        private NBool checkDateField;
        
        private NEnumOfLoadTypeEnum loadTypeField;
        
        private string registrationNumberField;
        
        private Identifier carrierIdField;
        
        private Identifier driverIdField;
        
        private string rfiTagIdField;
        
        private NEnumOfActiveIndicatorEnum activeIndField;
        
        private NEnumOfVehicleWeightRequiredEnum weighRequiredField;
        
        private NEnumOfVehicleWeightAcquiredMethodEnum weighAcquiredMethodField;
        
        private NInt weightInOutField;
        
        private NEnumOfVehicleWeightCheckEnum weightCheckField;
        
        private NBool useSameScaleField;
        
        private NDecimal waterCapacityField;
        
        private NDecimal maxFillingDegField;
        
        private NBool subjectToInspectionField;
        
        private NBool checkInTerminalStatusField;
        
        private NEnumOfVehicleLabSampleRequiredEnum labSampleRequiredField;
        
        private NDecimal weightToleranceField;
        
        private NEnumOfVehicleDisbursementTypeEnum disbursementTypeField;
        
        private string displayValueField;
        
        private string displaySortValueField;
        
        private NLong displaySortSequenceField;
        
        private ExternalIdentifier[] externalIdentifiersField;
        
        private VehicleCompartment[] vehicleCompartmentsField;
        
        private string createdByField;
        
        private NDateTime createdDateField;
        
        private string lastUpdatedByField;
        
        private NDateTime lastUpdatedDateField;
        
        private NLong customerField;
        
        private string ownerField;
        
        private NEnumOfRailCarTypeEnum railCarTypeField;
        
        private string dotClassField;
        
        private string[] equipmentField;
        
        private string adrCertificateField;
        
        private NDateTime adrExpirationDateField;
        
        private NDateTime leakTestDateField;
        
        private NDateTime hydraulicTestDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public Identifier VehicleId
        {
            get
            {
                return this.vehicleIdField;
            }
            set
            {
                this.vehicleIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CustomFieldInstances", IsNullable=true, Order=1)]
        public CustomFieldInstance[] CustomFieldInstances
        {
            get
            {
                return this.customFieldInstancesField;
            }
            set
            {
                this.customFieldInstancesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string VehicleCode
        {
            get
            {
                return this.vehicleCodeField;
            }
            set
            {
                this.vehicleCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string VehicleName
        {
            get
            {
                return this.vehicleNameField;
            }
            set
            {
                this.vehicleNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string VehicleDescription
        {
            get
            {
                return this.vehicleDescriptionField;
            }
            set
            {
                this.vehicleDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public NEnumOfVehicleTypeEnum VehicleType
        {
            get
            {
                return this.vehicleTypeField;
            }
            set
            {
                this.vehicleTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public Identifier LocationId
        {
            get
            {
                return this.locationIdField;
            }
            set
            {
                this.locationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public NDecimal VehicleTareWeight
        {
            get
            {
                return this.vehicleTareWeightField;
            }
            set
            {
                this.vehicleTareWeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public NDecimal VehicleWeightLimit
        {
            get
            {
                return this.vehicleWeightLimitField;
            }
            set
            {
                this.vehicleWeightLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public NEnumOfVehicleLoadingPositionEnum VehicleLoadingPosition
        {
            get
            {
                return this.vehicleLoadingPositionField;
            }
            set
            {
                this.vehicleLoadingPositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public NDateTime ExpiryDate
        {
            get
            {
                return this.expiryDateField;
            }
            set
            {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public NBool CheckDate
        {
            get
            {
                return this.checkDateField;
            }
            set
            {
                this.checkDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public NEnumOfLoadTypeEnum LoadType
        {
            get
            {
                return this.loadTypeField;
            }
            set
            {
                this.loadTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string RegistrationNumber
        {
            get
            {
                return this.registrationNumberField;
            }
            set
            {
                this.registrationNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public Identifier CarrierId
        {
            get
            {
                return this.carrierIdField;
            }
            set
            {
                this.carrierIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public Identifier DriverId
        {
            get
            {
                return this.driverIdField;
            }
            set
            {
                this.driverIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string RfiTagId
        {
            get
            {
                return this.rfiTagIdField;
            }
            set
            {
                this.rfiTagIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public NEnumOfActiveIndicatorEnum ActiveInd
        {
            get
            {
                return this.activeIndField;
            }
            set
            {
                this.activeIndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public NEnumOfVehicleWeightRequiredEnum WeighRequired
        {
            get
            {
                return this.weighRequiredField;
            }
            set
            {
                this.weighRequiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public NEnumOfVehicleWeightAcquiredMethodEnum WeighAcquiredMethod
        {
            get
            {
                return this.weighAcquiredMethodField;
            }
            set
            {
                this.weighAcquiredMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public NInt WeightInOut
        {
            get
            {
                return this.weightInOutField;
            }
            set
            {
                this.weightInOutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public NEnumOfVehicleWeightCheckEnum WeightCheck
        {
            get
            {
                return this.weightCheckField;
            }
            set
            {
                this.weightCheckField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public NBool UseSameScale
        {
            get
            {
                return this.useSameScaleField;
            }
            set
            {
                this.useSameScaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public NDecimal WaterCapacity
        {
            get
            {
                return this.waterCapacityField;
            }
            set
            {
                this.waterCapacityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public NDecimal MaxFillingDeg
        {
            get
            {
                return this.maxFillingDegField;
            }
            set
            {
                this.maxFillingDegField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public NBool SubjectToInspection
        {
            get
            {
                return this.subjectToInspectionField;
            }
            set
            {
                this.subjectToInspectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
        public NBool CheckInTerminalStatus
        {
            get
            {
                return this.checkInTerminalStatusField;
            }
            set
            {
                this.checkInTerminalStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public NEnumOfVehicleLabSampleRequiredEnum LabSampleRequired
        {
            get
            {
                return this.labSampleRequiredField;
            }
            set
            {
                this.labSampleRequiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public NDecimal WeightTolerance
        {
            get
            {
                return this.weightToleranceField;
            }
            set
            {
                this.weightToleranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public NEnumOfVehicleDisbursementTypeEnum DisbursementType
        {
            get
            {
                return this.disbursementTypeField;
            }
            set
            {
                this.disbursementTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public string DisplayValue
        {
            get
            {
                return this.displayValueField;
            }
            set
            {
                this.displayValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public string DisplaySortValue
        {
            get
            {
                return this.displaySortValueField;
            }
            set
            {
                this.displaySortValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=32)]
        public NLong DisplaySortSequence
        {
            get
            {
                return this.displaySortSequenceField;
            }
            set
            {
                this.displaySortSequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=33)]
        public ExternalIdentifier[] ExternalIdentifiers
        {
            get
            {
                return this.externalIdentifiersField;
            }
            set
            {
                this.externalIdentifiersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=34)]
        public VehicleCompartment[] VehicleCompartments
        {
            get
            {
                return this.vehicleCompartmentsField;
            }
            set
            {
                this.vehicleCompartmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string CreatedBy
        {
            get
            {
                return this.createdByField;
            }
            set
            {
                this.createdByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public NDateTime CreatedDate
        {
            get
            {
                return this.createdDateField;
            }
            set
            {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=37)]
        public string LastUpdatedBy
        {
            get
            {
                return this.lastUpdatedByField;
            }
            set
            {
                this.lastUpdatedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=38)]
        public NDateTime LastUpdatedDate
        {
            get
            {
                return this.lastUpdatedDateField;
            }
            set
            {
                this.lastUpdatedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=39)]
        public NLong Customer
        {
            get
            {
                return this.customerField;
            }
            set
            {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=40)]
        public string Owner
        {
            get
            {
                return this.ownerField;
            }
            set
            {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=41)]
        public NEnumOfRailCarTypeEnum RailCarType
        {
            get
            {
                return this.railCarTypeField;
            }
            set
            {
                this.railCarTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=42)]
        public string DotClass
        {
            get
            {
                return this.dotClassField;
            }
            set
            {
                this.dotClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=43)]
        public string[] Equipment
        {
            get
            {
                return this.equipmentField;
            }
            set
            {
                this.equipmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=44)]
        public string AdrCertificate
        {
            get
            {
                return this.adrCertificateField;
            }
            set
            {
                this.adrCertificateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=45)]
        public NDateTime AdrExpirationDate
        {
            get
            {
                return this.adrExpirationDateField;
            }
            set
            {
                this.adrExpirationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=46)]
        public NDateTime LeakTestDate
        {
            get
            {
                return this.leakTestDateField;
            }
            set
            {
                this.leakTestDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=47)]
        public NDateTime HydraulicTestDate
        {
            get
            {
                return this.hydraulicTestDateField;
            }
            set
            {
                this.hydraulicTestDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public partial class CustomFieldInstance : SynthesisEntity
    {
        
        private NLong customFieldInstanceIdField;
        
        private NLong entityIdField;
        
        private string fieldStringValueField;
        
        private NDecimal fieldNumericValueField;
        
        private NDateTime fieldDateTimeValueField;
        
        private CustomFieldMetaData customFieldMetaDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public NLong CustomFieldInstanceId
        {
            get
            {
                return this.customFieldInstanceIdField;
            }
            set
            {
                this.customFieldInstanceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public NLong EntityId
        {
            get
            {
                return this.entityIdField;
            }
            set
            {
                this.entityIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string FieldStringValue
        {
            get
            {
                return this.fieldStringValueField;
            }
            set
            {
                this.fieldStringValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public NDecimal FieldNumericValue
        {
            get
            {
                return this.fieldNumericValueField;
            }
            set
            {
                this.fieldNumericValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public NDateTime FieldDateTimeValue
        {
            get
            {
                return this.fieldDateTimeValueField;
            }
            set
            {
                this.fieldDateTimeValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public CustomFieldMetaData CustomFieldMetaData
        {
            get
            {
                return this.customFieldMetaDataField;
            }
            set
            {
                this.customFieldMetaDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://openseal.org/XmlSchema/1")]
    public partial class NDecimal
    {
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://openseal.org/XmlSchema/1")]
    public partial class NDateTime
    {
        
        private System.DateTime valueField;
        
        private DayOfWeek firstDayOfWeekField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public DayOfWeek FirstDayOfWeek
        {
            get
            {
                return this.firstDayOfWeekField;
            }
            set
            {
                this.firstDayOfWeekField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://openseal.org/XmlSchema/1")]
    public enum DayOfWeek
    {
        
        /// <remarks/>
        Sunday,
        
        /// <remarks/>
        Monday,
        
        /// <remarks/>
        Tuesday,
        
        /// <remarks/>
        Wednesday,
        
        /// <remarks/>
        Thursday,
        
        /// <remarks/>
        Friday,
        
        /// <remarks/>
        Saturday,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public partial class CustomFieldMetaData : SynthesisEntity
    {
        
        private NLong customFieldMetaDataIdField;
        
        private string nameField;
        
        private NEnumOfCustomFieldDataTypeEnum dataTypeField;
        
        private string entityNameField;
        
        private string entityKeyField;
        
        private string displayKeyField;
        
        private string defaultValueField;
        
        private NBool hasMultipleValuesField;
        
        private NBool isRequiredField;
        
        private string displayControlField;
        
        private NInt seqNumField;
        
        private NLong ruleClassIdField;
        
        private NEnumOfActiveIndicatorEnum activeIndicatorField;
        
        private string createdByField;
        
        private NDateTime createdDateField;
        
        private string lastUpdatedByField;
        
        private NDateTime lastUpdatedDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public NLong CustomFieldMetaDataId
        {
            get
            {
                return this.customFieldMetaDataIdField;
            }
            set
            {
                this.customFieldMetaDataIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public NEnumOfCustomFieldDataTypeEnum DataType
        {
            get
            {
                return this.dataTypeField;
            }
            set
            {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string EntityName
        {
            get
            {
                return this.entityNameField;
            }
            set
            {
                this.entityNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string EntityKey
        {
            get
            {
                return this.entityKeyField;
            }
            set
            {
                this.entityKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string DisplayKey
        {
            get
            {
                return this.displayKeyField;
            }
            set
            {
                this.displayKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string DefaultValue
        {
            get
            {
                return this.defaultValueField;
            }
            set
            {
                this.defaultValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public NBool HasMultipleValues
        {
            get
            {
                return this.hasMultipleValuesField;
            }
            set
            {
                this.hasMultipleValuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public NBool IsRequired
        {
            get
            {
                return this.isRequiredField;
            }
            set
            {
                this.isRequiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string DisplayControl
        {
            get
            {
                return this.displayControlField;
            }
            set
            {
                this.displayControlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public NInt SeqNum
        {
            get
            {
                return this.seqNumField;
            }
            set
            {
                this.seqNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public NLong RuleClassId
        {
            get
            {
                return this.ruleClassIdField;
            }
            set
            {
                this.ruleClassIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public NEnumOfActiveIndicatorEnum ActiveIndicator
        {
            get
            {
                return this.activeIndicatorField;
            }
            set
            {
                this.activeIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string CreatedBy
        {
            get
            {
                return this.createdByField;
            }
            set
            {
                this.createdByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public NDateTime CreatedDate
        {
            get
            {
                return this.createdDateField;
            }
            set
            {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string LastUpdatedBy
        {
            get
            {
                return this.lastUpdatedByField;
            }
            set
            {
                this.lastUpdatedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public NDateTime LastUpdatedDate
        {
            get
            {
                return this.lastUpdatedDateField;
            }
            set
            {
                this.lastUpdatedDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public partial class NEnumOfCustomFieldDataTypeEnum
    {
        
        private CustomFieldDataTypeEnum valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CustomFieldDataTypeEnum Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public enum CustomFieldDataTypeEnum
    {
        
        /// <remarks/>
        BYTE = 1,
        
        /// <remarks/>
        INT = 2,
        
        /// <remarks/>
        SHORT = 4,
        
        /// <remarks/>
        LONG = 8,
        
        /// <remarks/>
        BOOL = 16,
        
        /// <remarks/>
        STRING = 32,
        
        /// <remarks/>
        FLOAT = 64,
        
        /// <remarks/>
        DOUBLE = 128,
        
        /// <remarks/>
        DECIMAL = 256,
        
        /// <remarks/>
        DATETIME = 512,
        
        /// <remarks/>
        OPENSEAL_LOOKUP = 1024,
        
        /// <remarks/>
        CUSTOM_PLUGIN = 2048,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://openseal.org/XmlSchema/1")]
    public partial class NInt
    {
        
        private int valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public partial class NEnumOfActiveIndicatorEnum
    {
        
        private ActiveIndicatorEnum valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ActiveIndicatorEnum Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://openseal.org/XmlSchema/1")]
    public enum ActiveIndicatorEnum
    {
        
        /// <remarks/>
        INACTIVE = 1,
        
        /// <remarks/>
        ACTIVE = 2,
        
        /// <remarks/>
        ALL = 4,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VehicleCompartment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomFieldMetaData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomFieldInstance))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Vehicle))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public abstract partial class SynthesisEntity
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public partial class VehicleCompartment : SynthesisEntity
    {
        
        private Identifier compartmentIdField;
        
        private Identifier vehicleIdField;
        
        private NLong compartmentNumberField;
        
        private NDecimal capacityField;
        
        private NLong productIdField;
        
        private string createdByField;
        
        private NDateTime createdDateField;
        
        private string lastUpdatedByField;
        
        private NDateTime lastUpdatedDateField;
        
        private NEnumOfOutageTypeEnum outageTypeField;
        
        private NDecimal outageValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public Identifier CompartmentId
        {
            get
            {
                return this.compartmentIdField;
            }
            set
            {
                this.compartmentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public Identifier VehicleId
        {
            get
            {
                return this.vehicleIdField;
            }
            set
            {
                this.vehicleIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public NLong CompartmentNumber
        {
            get
            {
                return this.compartmentNumberField;
            }
            set
            {
                this.compartmentNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public NDecimal Capacity
        {
            get
            {
                return this.capacityField;
            }
            set
            {
                this.capacityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public NLong ProductId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string CreatedBy
        {
            get
            {
                return this.createdByField;
            }
            set
            {
                this.createdByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public NDateTime CreatedDate
        {
            get
            {
                return this.createdDateField;
            }
            set
            {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string LastUpdatedBy
        {
            get
            {
                return this.lastUpdatedByField;
            }
            set
            {
                this.lastUpdatedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public NDateTime LastUpdatedDate
        {
            get
            {
                return this.lastUpdatedDateField;
            }
            set
            {
                this.lastUpdatedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public NEnumOfOutageTypeEnum OutageType
        {
            get
            {
                return this.outageTypeField;
            }
            set
            {
                this.outageTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public NDecimal OutageValue
        {
            get
            {
                return this.outageValueField;
            }
            set
            {
                this.outageValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public partial class NEnumOfOutageTypeEnum
    {
        
        private OutageTypeEnum valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public OutageTypeEnum Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public enum OutageTypeEnum
    {
        
        /// <remarks/>
        UNKNOWN = 1,
        
        /// <remarks/>
        VOLUME = 2,
        
        /// <remarks/>
        PERCENTAGE = 4,
        
        /// <remarks/>
        INCREMENT = 8,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public partial class NEnumOfVehicleTypeEnum
    {
        
        private VehicleTypeEnum valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VehicleTypeEnum Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public enum VehicleTypeEnum
    {
        
        /// <remarks/>
        UNKNOWN = 1,
        
        /// <remarks/>
        TRACTOR_TRUCK = 2,
        
        /// <remarks/>
        TANK_TRAILER = 4,
        
        /// <remarks/>
        RIGID = 8,
        
        /// <remarks/>
        TOWED_TRAILER = 16,
        
        /// <remarks/>
        CONTAINER_TRAILER = 32,
        
        /// <remarks/>
        RAILCAR = 64,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public partial class NEnumOfVehicleLoadingPositionEnum
    {
        
        private VehicleLoadingPositionEnum valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VehicleLoadingPositionEnum Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public enum VehicleLoadingPositionEnum
    {
        
        /// <remarks/>
        UNKNOWN = 1,
        
        /// <remarks/>
        ANY = 2,
        
        /// <remarks/>
        REAR = 4,
        
        /// <remarks/>
        RIGHT = 8,
        
        /// <remarks/>
        LEFT = 16,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public partial class NEnumOfLoadTypeEnum
    {
        
        private LoadTypeEnum valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LoadTypeEnum Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public enum LoadTypeEnum
    {
        
        /// <remarks/>
        UNKNOWN,
        
        /// <remarks/>
        SCHED,
        
        /// <remarks/>
        LIMIT,
        
        /// <remarks/>
        QUOTA,
        
        /// <remarks/>
        SUPER,
        
        /// <remarks/>
        METER_CALIBRATION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public partial class NEnumOfVehicleWeightRequiredEnum
    {
        
        private VehicleWeightRequiredEnum valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VehicleWeightRequiredEnum Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public enum VehicleWeightRequiredEnum
    {
        
        /// <remarks/>
        UNKNOWN = 1,
        
        /// <remarks/>
        NOT_REQUIRED = 2,
        
        /// <remarks/>
        IN_WEIGHT = 4,
        
        /// <remarks/>
        OUT_WEIGHT = 8,
        
        /// <remarks/>
        BOTH_IN_OUT = 16,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public partial class NEnumOfVehicleWeightAcquiredMethodEnum
    {
        
        private VehicleWeightAcquiredMethodEnum valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VehicleWeightAcquiredMethodEnum Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public enum VehicleWeightAcquiredMethodEnum
    {
        
        /// <remarks/>
        UNKNOWN = 1,
        
        /// <remarks/>
        USING_WEIGHBRIDGE = 2,
        
        /// <remarks/>
        PROMPT_AT_LOADING_BAY = 4,
        
        /// <remarks/>
        MANUAL_USING_GUI = 8,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public partial class NEnumOfVehicleWeightCheckEnum
    {
        
        private VehicleWeightCheckEnum valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VehicleWeightCheckEnum Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public enum VehicleWeightCheckEnum
    {
        
        /// <remarks/>
        UNKNOWN = 1,
        
        /// <remarks/>
        DO_NOT_CHECK_WEIGHT = 2,
        
        /// <remarks/>
        CHECK_WEIGHT = 4,
        
        /// <remarks/>
        REJECT_WEIGHT = 8,
        
        /// <remarks/>
        ACCEPT_WEIGHT = 16,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public partial class NEnumOfVehicleLabSampleRequiredEnum
    {
        
        private VehicleLabSampleRequiredEnum valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VehicleLabSampleRequiredEnum Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public enum VehicleLabSampleRequiredEnum
    {
        
        /// <remarks/>
        UNKNOWN = 1,
        
        /// <remarks/>
        NOT_REQUIRED = 2,
        
        /// <remarks/>
        REQUIRED_BEFORE_MOVEMENT = 4,
        
        /// <remarks/>
        REQUIRED_AFTER_MOVEMENT = 8,
        
        /// <remarks/>
        BOTH = 16,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public partial class NEnumOfVehicleDisbursementTypeEnum
    {
        
        private VehicleDisbursementTypeEnum valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VehicleDisbursementTypeEnum Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public enum VehicleDisbursementTypeEnum
    {
        
        /// <remarks/>
        UNKNOWN = 1,
        
        /// <remarks/>
        FACILITY = 2,
        
        /// <remarks/>
        DELIVERY = 4,
        
        /// <remarks/>
        RECEIPT = 8,
        
        /// <remarks/>
        BOTH = 16,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public partial class ExternalIdentifier
    {
        
        private NLong transformItemIdField;
        
        private NLong transformIdField;
        
        private string transformNameField;
        
        private string externalNumLabelField;
        
        private NLong externalNumField;
        
        private string externalStringLabelField;
        
        private string externalStringField;
        
        private string transformStringLabelField;
        
        private string transformStringField;
        
        private string transformString2Field;
        
        private string transformNumLabelField;
        
        private NLong transformNumField;
        
        private bool failIfNotTranslatedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public NLong TransformItemId
        {
            get
            {
                return this.transformItemIdField;
            }
            set
            {
                this.transformItemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public NLong TransformId
        {
            get
            {
                return this.transformIdField;
            }
            set
            {
                this.transformIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string TransformName
        {
            get
            {
                return this.transformNameField;
            }
            set
            {
                this.transformNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string ExternalNumLabel
        {
            get
            {
                return this.externalNumLabelField;
            }
            set
            {
                this.externalNumLabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public NLong ExternalNum
        {
            get
            {
                return this.externalNumField;
            }
            set
            {
                this.externalNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string ExternalStringLabel
        {
            get
            {
                return this.externalStringLabelField;
            }
            set
            {
                this.externalStringLabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string ExternalString
        {
            get
            {
                return this.externalStringField;
            }
            set
            {
                this.externalStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string TransformStringLabel
        {
            get
            {
                return this.transformStringLabelField;
            }
            set
            {
                this.transformStringLabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string TransformString
        {
            get
            {
                return this.transformStringField;
            }
            set
            {
                this.transformStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string TransformString2
        {
            get
            {
                return this.transformString2Field;
            }
            set
            {
                this.transformString2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string TransformNumLabel
        {
            get
            {
                return this.transformNumLabelField;
            }
            set
            {
                this.transformNumLabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public NLong TransformNum
        {
            get
            {
                return this.transformNumField;
            }
            set
            {
                this.transformNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool FailIfNotTranslated
        {
            get
            {
                return this.failIfNotTranslatedField;
            }
            set
            {
                this.failIfNotTranslatedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public partial class NEnumOfRailCarTypeEnum
    {
        
        private RailCarTypeEnum valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RailCarTypeEnum Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public enum RailCarTypeEnum
    {
        
        /// <remarks/>
        UNKNOWN = 1,
        
        /// <remarks/>
        STANDARD = 2,
        
        /// <remarks/>
        DOME = 4,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public partial class WsGetVehiclesRequest : WsRequest
    {
        
        private Identifier systemIdField;
        
        private Identifier locationIdField;
        
        private string vehicleCodeField;
        
        private string vehicleNameField;
        
        private NInt vehicleTypeField;
        
        private NEnumOfActiveIndicatorEnum activeIndField;
        
        private NBool includeVehicleCompartmentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public Identifier SystemId
        {
            get
            {
                return this.systemIdField;
            }
            set
            {
                this.systemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public Identifier LocationId
        {
            get
            {
                return this.locationIdField;
            }
            set
            {
                this.locationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string VehicleCode
        {
            get
            {
                return this.vehicleCodeField;
            }
            set
            {
                this.vehicleCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string VehicleName
        {
            get
            {
                return this.vehicleNameField;
            }
            set
            {
                this.vehicleNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public NInt VehicleType
        {
            get
            {
                return this.vehicleTypeField;
            }
            set
            {
                this.vehicleTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public NEnumOfActiveIndicatorEnum ActiveInd
        {
            get
            {
                return this.activeIndField;
            }
            set
            {
                this.activeIndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public NBool IncludeVehicleCompartments
        {
            get
            {
                return this.includeVehicleCompartmentsField;
            }
            set
            {
                this.includeVehicleCompartmentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.entessa.com/synthesisSchema/1/")]
    public partial class WsVehicleResponse : WsResponse
    {
        
        private Vehicle[] vehiclesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Vehicle[] Vehicles
        {
            get
            {
                return this.vehiclesField;
            }
            set
            {
                this.vehiclesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface VehicleServiceChannel : ServiceReference1.VehicleService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class VehicleServiceClient : System.ServiceModel.ClientBase<ServiceReference1.VehicleService>, ServiceReference1.VehicleService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public VehicleServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(VehicleServiceClient.GetBindingForEndpoint(endpointConfiguration), VehicleServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VehicleServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(VehicleServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VehicleServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(VehicleServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VehicleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.WsVehicleResponse> GetVehicleAsync(ServiceReference1.WsGetVehicleRequest req)
        {
            return base.Channel.GetVehicleAsync(req);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.WsVehicleResponse> GetVehiclesAsync(ServiceReference1.WsGetVehiclesRequest req)
        {
            return base.Channel.GetVehiclesAsync(req);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.WsVehicleResponse> SaveVehicleAsync(ServiceReference1.WsSaveVehicleRequest req)
        {
            return base.Channel.SaveVehicleAsync(req);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_VehicleService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.TransportCredentialOnly;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Basic;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_VehicleService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.TransportCredentialOnly;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Windows;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_VehicleService2))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Basic;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_VehicleService3))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Windows;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_VehicleService))
            {
                return new System.ServiceModel.EndpointAddress("http://qa.synthesis.itzoil.com:14094/v1/VehicleService/soap");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_VehicleService1))
            {
                return new System.ServiceModel.EndpointAddress("http://qa.synthesis.itzoil.com:14094/v1/VehicleService/soapWin");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_VehicleService2))
            {
                return new System.ServiceModel.EndpointAddress("https://qa.synthesis.itzoil.com:14095/v1/VehicleService/soapSsl");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_VehicleService3))
            {
                return new System.ServiceModel.EndpointAddress("https://qa.synthesis.itzoil.com:14095/v1/VehicleService/soapSslWin");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_VehicleService,
            
            BasicHttpBinding_VehicleService1,
            
            BasicHttpBinding_VehicleService2,
            
            BasicHttpBinding_VehicleService3,
        }
    }
}
